POST http://localhost:3000/register/
Content-Type: application/json

{
  "username": "adam_richa",
  "name": "Adam Richard",
  "password": "richna",
  "gender": "male",
  "location": "Detroit"
}


###

POST http://localhost:3000/login/
Content-Type: application/json

{
  "username": "adam_richard",
  "password": "richard_567"
}

###

PuT http://localhost:3000/change-password/
Content-Type: application/json

{
  "username": "adam_richard",
  "oldPassword": "richard_567",
  "newPassword": "richard@123"
}